import type { Client, Segment } from "./data";

// Lista clienti ufficiale fornita da Daniele (Dic 2026). Import idempotente: applicato una volta sola
// tramite il flag __clientsImportV7 in store.ts/migrate.
export const CLIENT_IMPORT_V7: { name: string; phones: string[]; segment: "inattivi"|"nuovi"|"occasionali"|"abituali"|"top" }[] = [
  { name: "Filippo Bar stop", phones: ["+393284440262"], segment: "abituali" },
  { name: "Giulio Falso", phones: ["+393458381604"], segment: "abituali" },
  { name: "Lorenza Russo", phones: ["+393282717906"], segment: "inattivi" },
  { name: "Angelo Borrelli", phones: [], segment: "inattivi" },
  { name: "Gabriella Di cola", phones: ["+393664083699"], segment: "inattivi" },
  { name: "Roberto Orlando", phones: ["+393333168946"], segment: "inattivi" },
  { name: "Antonio Mignano", phones: [], segment: "inattivi" },
  { name: "Liberino", phones: ["+393394497000"], segment: "inattivi" },
  { name: "Valeria La stazza", phones: ["+393475963526"], segment: "inattivi" },
  { name: "Gabriele Petrone", phones: [], segment: "inattivi" },
  { name: "Mario Moscati", phones: ["+393475324057"], segment: "abituali" },
  { name: "Antonella Conte", phones: ["+393273080243"], segment: "inattivi" },
  { name: "Luca Fusco", phones: [], segment: "inattivi" },
  { name: "Eleonora Bonoli", phones: ["+393381373707"], segment: "inattivi" },
  { name: "Emilio Ianniello", phones: [], segment: "inattivi" },
  { name: "Annamaria Sciorio", phones: [], segment: "inattivi" },
  { name: "Ed Testa", phones: ["+393473052503"], segment: "inattivi" },
  { name: "Pietro Mendico", phones: ["+393394611615"], segment: "inattivi" },
  { name: "Marlena Polacca amica zia", phones: [], segment: "inattivi" },
  { name: "Luigi Forte", phones: ["+393496613933"], segment: "inattivi" },
  { name: "Pina Falso", phones: [], segment: "inattivi" },
  { name: "Marilena Marzullo", phones: ["+393896047347"], segment: "inattivi" },
  { name: "Ciro Russo", phones: ["+393465876810"], segment: "inattivi" },
  { name: "Giulia Del vecchio", phones: ["+393471478808"], segment: "inattivi" },
  { name: "Domenico Paliotta", phones: ["+393406244174"], segment: "inattivi" },
  { name: "Ferdinando Ianniello", phones: ["+393890083457"], segment: "inattivi" },
  { name: "Cristina Cinquanta", phones: ["+393282867187"], segment: "inattivi" },
  { name: "Serena Casale", phones: ["+393888724985"], segment: "abituali" },
  { name: "Savore Carbone", phones: ["+393471074503"], segment: "abituali" },
  { name: "Ornella Di biasio", phones: ["+393492584388"], segment: "inattivi" },
  { name: "Enza Costanzo", phones: ["+393403868608"], segment: "inattivi" },
  { name: "Sabrina La valle", phones: [], segment: "inattivi" },
  { name: "Alessandro Iannotta", phones: [], segment: "inattivi" },
  { name: "Antonella D'antonio", phones: [], segment: "inattivi" },
  { name: "Angelo Ionta", phones: [], segment: "inattivi" },
  { name: "Letizia Lanzafame", phones: ["+393801951375"], segment: "inattivi" },
  { name: "Maria Civita Gallucci", phones: ["+393494525270"], segment: "inattivi" },
  { name: "Egidio Riccardi", phones: [], segment: "inattivi" },
  { name: "Antonio Pandolfo", phones: [], segment: "inattivi" },
  { name: "Massimo Falso", phones: ["+393386836905"], segment: "inattivi" },
  { name: "Tina Cinque", phones: ["+393387536465"], segment: "inattivi" },
  { name: "Gabriella Franco", phones: [], segment: "inattivi" },
  { name: "Antonietta Mattei", phones: [], segment: "inattivi" },
  { name: "Elisabetta Romanelli", phones: ["+393291911823"], segment: "inattivi" },
  { name: "Francesca Tufino", phones: [], segment: "inattivi" },
  { name: "Alessandra Polverino", phones: ["+393498633085"], segment: "abituali" },
  { name: "Gelsomina Timuneri", phones: ["+390771674698"], segment: "inattivi" },
  { name: "Vittorio Caramanica", phones: ["+393338693967"], segment: "inattivi" },
  { name: "Milena Dell uomo", phones: ["+393279767494"], segment: "inattivi" },
  { name: "Federica Russo", phones: ["+393792265703"], segment: "abituali" },
  { name: "Sergio Formia", phones: [], segment: "abituali" },
  { name: "Tina Bortoloni", phones: [], segment: "inattivi" },
  { name: "Stefania Mallozzi", phones: ["+393404838008"], segment: "abituali" },
  { name: "Luigi Sabatino", phones: ["+393925700205"], segment: "inattivi" },
  { name: "Giovanna", phones: [], segment: "inattivi" },
  { name: "Sonia Cardillo", phones: [], segment: "inattivi" },
  { name: "Pietropaolo Viscovo", phones: ["+393332336088"], segment: "inattivi" },
  { name: "Biseco", phones: ["+393467382538"], segment: "inattivi" },
  { name: "Adriano Veronica", phones: [], segment: "inattivi" },
  { name: "Rosa Scarpellino", phones: ["+393917665177"], segment: "inattivi" },
  { name: "Calogero Timuneri", phones: [], segment: "abituali" },
  { name: "Enzo Perfetto", phones: ["+393346576287","+393518003537"], segment: "abituali" },
  { name: "Enza Parente", phones: ["+393406785671"], segment: "abituali" },
  { name: "Michela La valle", phones: [], segment: "inattivi" },
  { name: "Enzo Testa", phones: ["+393402158450"], segment: "abituali" },
  { name: "Roberto Tutto gelo", phones: [], segment: "inattivi" },
  { name: "Enzo Rocco", phones: ["+393665379973"], segment: "abituali" },
  { name: "Mario Ottaviano", phones: ["+393807099884"], segment: "abituali" },
  { name: "Cosimo Corrente", phones: ["+393347106781"], segment: "abituali" },
  { name: "Andrea Micarelli", phones: ["+393927813314"], segment: "inattivi" },
  { name: "Paolo D'Alessandro", phones: [], segment: "inattivi" },
  { name: "Franco Vellucci", phones: ["+393478141752"], segment: "inattivi" },
  { name: "Rocco Damiano", phones: ["+393486720315"], segment: "inattivi" },
  { name: "Liliana Falso", phones: [], segment: "inattivi" },
  { name: "Domenico Donofrio", phones: [], segment: "inattivi" },
  { name: "Antonietta Maccio", phones: [], segment: "inattivi" },
  { name: "Stefano Russo", phones: ["+393284053216"], segment: "abituali" },
  { name: "Priscilla Ciufo", phones: ["+393207956987"], segment: "inattivi" },
  { name: "Antonietta Tartaglia", phones: [], segment: "abituali" },
  { name: "Attilio Di nardo", phones: ["+393400810196"], segment: "abituali" },
  { name: "Giovanni Del Giudice", phones: [], segment: "inattivi" },
  { name: "Immacolata Verricco", phones: [], segment: "inattivi" },
  { name: "Mamma Doriano", phones: [], segment: "inattivi" },
  { name: "Giovanni Cappuccia", phones: ["+393714638227"], segment: "inattivi" },
  { name: "Antonio Giuliano", phones: [], segment: "inattivi" },
  { name: "Gianluca Testa", phones: [], segment: "inattivi" },
  { name: "Filippo D'aprano", phones: [], segment: "inattivi" },
  { name: "Vincenzo Moretta", phones: [], segment: "inattivi" },
  { name: "Damiano Ianniello", phones: [], segment: "inattivi" },
  { name: "Belinda Coviello", phones: [], segment: "inattivi" },
  { name: "Tina Di Paola", phones: ["+393487473759"], segment: "inattivi" },
  { name: "Riccardo Di mambro", phones: [], segment: "inattivi" },
  { name: "Giulio Gaveglia", phones: ["+393483630582"], segment: "abituali" },
  { name: "Ivano De turi", phones: [], segment: "inattivi" },
  { name: "Michela Di bello", phones: [], segment: "inattivi" },
  { name: "Renato Vigorito", phones: [], segment: "inattivi" },
  { name: "Romina Ottaviano", phones: [], segment: "inattivi" },
  { name: "Tiziana", phones: [], segment: "inattivi" },
  { name: "Carmine Vellucci", phones: ["+393382087223"], segment: "inattivi" },
  { name: "Stefania Casale", phones: [], segment: "inattivi" },
  { name: "Rosa Vellucci", phones: [], segment: "inattivi" },
  { name: "Antonietta Falso", phones: ["+393428296589"], segment: "inattivi" },
  { name: "Alessandro Mallozzi", phones: [], segment: "inattivi" },
  { name: "Antonio Corrente", phones: ["+393476971367"], segment: "abituali" },
  { name: "Antonella Fusco", phones: ["+393383805902"], segment: "inattivi" },
  { name: "Onorio", phones: [], segment: "inattivi" },
  { name: "Ilaria Magnante", phones: [], segment: "inattivi" },
  { name: "Roberto Assaiante", phones: [], segment: "inattivi" },
  { name: "Rocco Napolitano", phones: [], segment: "inattivi" },
  { name: "Giuseppe Forte", phones: [], segment: "inattivi" },
  { name: "Mauro Romanelli", phones: ["+393273778252"], segment: "inattivi" },
  { name: "Marcello Taddeo", phones: [], segment: "inattivi" },
  { name: "Gaspare Coviello", phones: ["+393287473734"], segment: "inattivi" },
  { name: "Enzo Riccardi", phones: ["+393406785672"], segment: "abituali" },
  { name: "Nonna Edilia", phones: [], segment: "inattivi" },
  { name: "Antonio Verrico", phones: [], segment: "inattivi" },
  { name: "Domenico Rocco", phones: [], segment: "abituali" },
  { name: "Aniello Camera", phones: [], segment: "inattivi" },
  { name: "Annamaria Pampena", phones: [], segment: "inattivi" },
  { name: "Roberto Falso", phones: [], segment: "inattivi" },
  { name: "Nadia Casaburi", phones: [], segment: "inattivi" },
  { name: "Patrizio", phones: [], segment: "inattivi" },
  { name: "Paolo Testa", phones: [], segment: "inattivi" },
  { name: "Gilda Di nardo", phones: [], segment: "inattivi" },
  { name: "Giovanni Cassetta", phones: ["+393403783266"], segment: "inattivi" },
  { name: "Domenico Nei", phones: [], segment: "inattivi" },
  { name: "Carolina La starza", phones: [], segment: "inattivi" },
  { name: "Trx Mallozzi", phones: [], segment: "inattivi" },
  { name: "Evelina Coviello", phones: ["+393284158100"], segment: "abituali" },
  { name: "Michele Di tano", phones: [], segment: "inattivi" },
  { name: "Domenico Polizzano", phones: [], segment: "inattivi" },
  { name: "Giusy De meo", phones: ["+13396344336","+393396344336"], segment: "abituali" },
  { name: "Giulio Romanelli", phones: [], segment: "inattivi" },
  { name: "Vincenzo Sessa", phones: ["+393477830861"], segment: "abituali" },
  { name: "Patrizio Vellucci", phones: [], segment: "inattivi" },
  { name: "Antonio Di fiore", phones: [], segment: "inattivi" },
  { name: "Pino Capasso", phones: [], segment: "inattivi" },
  { name: "Giovanni Di principe", phones: [], segment: "inattivi" },
  { name: "Marco Paldolfo", phones: ["+393883410878"], segment: "inattivi" },
  { name: "Camilla Perugina", phones: [], segment: "inattivi" },
  { name: "Angelo Cinquanta", phones: ["+393384025499"], segment: "abituali" },
  { name: "Giuseppe Vivard", phones: [], segment: "inattivi" },
  { name: "Testa Mauro", phones: [], segment: "inattivi" },
  { name: "Cristian Ieno", phones: [], segment: "inattivi" },
  { name: "Assunta D'aprano", phones: [], segment: "inattivi" },
  { name: "Katia Casale", phones: [], segment: "inattivi" },
  { name: "Aldo Testa", phones: [], segment: "inattivi" },
  { name: "Silvano Di Marco", phones: ["+393403876863"], segment: "abituali" },
  { name: "Antonio Di paola", phones: [], segment: "inattivi" },
  { name: "Giuseppe Casale", phones: [], segment: "inattivi" },
  { name: "Anna Riccardi", phones: ["+393209450352"], segment: "inattivi" },
  { name: "Anna Fischione", phones: ["+393935636674"], segment: "inattivi" },
  { name: "Teresa Giugliano", phones: [], segment: "inattivi" },
  { name: "Paola Poccia", phones: [], segment: "inattivi" },
  { name: "Maria Gambali", phones: [], segment: "inattivi" },
  { name: "Antonio Di rienzo", phones: ["+393770853631"], segment: "abituali" },
  { name: "Tommaso La rocca", phones: [], segment: "inattivi" },
  { name: "Occhiali Vellucci", phones: [], segment: "inattivi" },
  { name: "Pina Milano", phones: ["+393888976356"], segment: "inattivi" },
  { name: "Antonio Verricco", phones: [], segment: "inattivi" },
  { name: "Sabrina Capodiferro", phones: ["+393276922625"], segment: "inattivi" },
  { name: "Rosalia Marino", phones: ["+393486029816"], segment: "inattivi" },
  { name: "Roberto Napolitano", phones: [], segment: "inattivi" },
  { name: "Angelo Polidoro", phones: [], segment: "inattivi" },
  { name: "Lina Petrucelli", phones: [], segment: "inattivi" },
  { name: "Angelo Di cicco", phones: ["+393382195903"], segment: "inattivi" },
  { name: "Orlandino Riccardi", phones: [], segment: "inattivi" },
  { name: "Camillo Panzanella", phones: ["+393473290801"], segment: "inattivi" },
  { name: "Sandro Ianniello", phones: [], segment: "inattivi" },
  { name: "Emilio Parascandalo", phones: [], segment: "inattivi" },
  { name: "Raffaele Fiorino", phones: [], segment: "inattivi" },
  { name: "Aquilino La starza", phones: ["+393482841241"], segment: "inattivi" },
  { name: "Patrizio Palermiti", phones: ["+393388815441"], segment: "inattivi" },
  { name: "Angelo Mazzucco", phones: [], segment: "inattivi" },
  { name: "Monica La valle", phones: ["+393452237802"], segment: "inattivi" },
  { name: "Mina Tirimbo", phones: ["+393480869936"], segment: "inattivi" },
  { name: "Daniela Di guida", phones: ["+393477265008"], segment: "inattivi" },
  { name: "Daniele Sciorio", phones: [], segment: "inattivi" },
  { name: "Cosma Ionta", phones: ["+390771675529"], segment: "inattivi" },
  { name: "Angela Maria Ianniello", phones: ["+393284121682"], segment: "inattivi" },
  { name: "Falso Francesca", phones: [], segment: "inattivi" },
  { name: "Cinzia Pellegrini", phones: [], segment: "inattivi" },
  { name: "Antonio Di Vito", phones: ["+393290853600"], segment: "inattivi" },
  { name: "Adriana D'aprano", phones: ["+393274485755"], segment: "inattivi" },
  { name: "Angelo Darienzo", phones: ["+393496417472"], segment: "inattivi" },
  { name: "Valter Granelli", phones: [], segment: "inattivi" },
  { name: "Adamo Mazzante", phones: ["+393804670212"], segment: "inattivi" },
  { name: "Antonio Talesco", phones: ["+393791545943"], segment: "inattivi" },
  { name: "Aurora Pandolfo", phones: [], segment: "inattivi" },
  { name: "Maria Teresa Verrico", phones: ["+393405064093"], segment: "inattivi" },
  { name: "Filippo Conte", phones: ["+393335769523"], segment: "inattivi" },
  { name: "Matteo Pugliese", phones: ["+393408656265"], segment: "inattivi" },
  { name: "Filippo Di Vito", phones: ["+393346174203"], segment: "inattivi" },
  { name: "Mario Falso", phones: ["+393286866916"], segment: "inattivi" },
  { name: "Manila Riccardi", phones: ["+393209733253"], segment: "inattivi" },
  { name: "Stefano Di bello", phones: ["+393402558973"], segment: "inattivi" },
  { name: "Freddy Putz", phones: [], segment: "inattivi" },
  { name: "Nello Klimabus", phones: ["+393487557600"], segment: "abituali" },
  { name: "Pasqualino Poletta", phones: [], segment: "inattivi" },
  { name: "Fernando Galiardi", phones: ["+393485853756"], segment: "inattivi" },
  { name: "Alessandra Romano", phones: ["+393476103560"], segment: "inattivi" },
  { name: "Signora occhiali simpatica", phones: [], segment: "inattivi" },
  { name: "Domenico D'aprano", phones: [], segment: "inattivi" },
  { name: "Antonella Massimo", phones: [], segment: "inattivi" },
  { name: "Camillo Vincenzo", phones: ["+393313773874"], segment: "inattivi" },
  { name: "Mallozzi", phones: [], segment: "inattivi" },
  { name: "Angelina Mc", phones: ["+393402767516"], segment: "inattivi" },
  { name: "Terry Fiorillo", phones: ["+393803888465"], segment: "inattivi" },
  { name: "Lorenza Di biasio", phones: [], segment: "inattivi" },
  { name: "Avagliano", phones: [], segment: "inattivi" },
  { name: "Massimo D'angio", phones: [], segment: "inattivi" },
  { name: "Celestino Buonamano", phones: [], segment: "inattivi" },
  { name: "Giancarlo Simeone", phones: [], segment: "inattivi" },
  { name: "Luigi", phones: [], segment: "inattivi" },
  { name: "Francesca Frungillo", phones: [], segment: "inattivi" },
  { name: "Pina Liberato", phones: [], segment: "inattivi" },
  { name: "Simona Di vanni", phones: ["+393402314227"], segment: "inattivi" },
  { name: "Rosetta Bellucci", phones: [], segment: "inattivi" },
  { name: "Pasqualina Testa", phones: [], segment: "inattivi" },
  { name: "Alessandro Casale", phones: [], segment: "inattivi" },
  { name: "Piero Lucciola", phones: ["+393519271968"], segment: "inattivi" },
  { name: "Damiano Ionta", phones: ["+393406110467"], segment: "abituali" },
  { name: "Alba", phones: [], segment: "inattivi" },
  { name: "Azienda agricola Campese", phones: [], segment: "inattivi" },
  { name: "Nando Ragonese", phones: ["+390771672099"], segment: "inattivi" },
  { name: "Mario Ianniello", phones: [], segment: "inattivi" },
  { name: "Gildo Verrico", phones: [], segment: "inattivi" },
  { name: "Donato Autoscuola", phones: [], segment: "inattivi" },
  { name: "Filomena Di Martino", phones: ["+393270127017"], segment: "inattivi" },
  { name: "Alessio Di riccaro", phones: ["+393286325954"], segment: "inattivi" },
  { name: "Daniel Ieno", phones: ["+393452190449"], segment: "inattivi" },
  { name: "Monica Amiri", phones: ["+393791783247"], segment: "inattivi" },
  { name: "Arturo Nocella", phones: ["+393471875999"], segment: "inattivi" },
  { name: "Maria Fiorillo", phones: ["+393425185400"], segment: "inattivi" },
  { name: "Francesco Filosa", phones: ["+393271636975"], segment: "inattivi" },
  { name: "Salvatore Fabozzi", phones: ["+393204746330"], segment: "inattivi" },
  { name: "Annamaria De filippis", phones: [], segment: "inattivi" },
  { name: "Agostino Giaccone", phones: [], segment: "inattivi" },
  { name: "Orlando Testa", phones: [], segment: "inattivi" },
  { name: "Cristina Vellucci", phones: ["+393883871327"], segment: "inattivi" },
  { name: "Miura Errante", phones: ["+393483000625"], segment: "inattivi" },
  { name: "Salvatore Crolla", phones: ["+393291888881"], segment: "inattivi" },
  { name: "Massimo Mazzucco", phones: ["+393393687547"], segment: "inattivi" },
  { name: "Laura Alicandro", phones: ["+393498716084"], segment: "inattivi" },
  { name: "Teresa Polidoro", phones: ["+393406200172"], segment: "inattivi" },
  { name: "Roberto Di rollo", phones: ["+393462419014"], segment: "inattivi" },
  { name: "Sabatino Lucci", phones: [], segment: "inattivi" },
  { name: "Paolo Ciorra", phones: [], segment: "inattivi" },
  { name: "Gaetano Iannotta", phones: ["+393455090758"], segment: "inattivi" },
  { name: "Paola Roccia", phones: ["+393288750630"], segment: "inattivi" },
  { name: "Fiorella Ianniello", phones: ["+393297034629"], segment: "inattivi" },
  { name: "Lina Gagliardi", phones: ["+393776810248"], segment: "inattivi" },
  { name: "Gianluca Rossini", phones: ["+393277470614"], segment: "inattivi" },
  { name: "Carla De Petrillo", phones: ["+390771608459","+393482229760"], segment: "inattivi" },
  { name: "Linda Mallozzi", phones: [], segment: "inattivi" },
  { name: "Raffaella Cavallo", phones: [], segment: "inattivi" },
  { name: "Katia Ficaio", phones: [], segment: "inattivi" },
  { name: "Angela Corelli", phones: ["+393452410744"], segment: "inattivi" },
  { name: "Paride Palazzo", phones: ["+393338253818"], segment: "inattivi" },
  { name: "Maria assunta Cinquanta", phones: ["+393475124934"], segment: "inattivi" },
  { name: "Fioraio Rossillo", phones: [], segment: "inattivi" },
  { name: "Luciano Belzotti", phones: ["+393292609051","+393204438687"], segment: "top" },
  { name: "Alessio Di viccaro", phones: [], segment: "inattivi" },
  { name: "Marco Esposito", phones: ["+491621705064"], segment: "inattivi" },
  { name: "Gina Pandolfo", phones: ["+393296334843"], segment: "inattivi" },
  { name: "Anna Tosti", phones: ["+393394952802"], segment: "inattivi" },
  { name: "Pina Ianniello", phones: ["+393492585477"], segment: "inattivi" },
  { name: "Laura Iacobucci", phones: [], segment: "inattivi" },
  { name: "Angela Candice", phones: ["+393488892867"], segment: "inattivi" },
  { name: "Attilio Capezzano", phones: ["+393496733056"], segment: "inattivi" },
  { name: "Giovanni Alfano", phones: ["+393771842310"], segment: "inattivi" },
  { name: "Jessicca Cassetta", phones: [], segment: "inattivi" },
  { name: "Di mambro", phones: [], segment: "inattivi" },
  { name: "Filippo Polidoro", phones: ["+393914617627"], segment: "inattivi" },
  { name: "Fabio Barbon", phones: ["+393278724148"], segment: "inattivi" },
  { name: "Stefania Valente", phones: ["+393899951712"], segment: "inattivi" },
  { name: "Pasquale Carbone", phones: [], segment: "inattivi" },
  { name: "Massimo Marocco", phones: ["+393914282477"], segment: "inattivi" },
  { name: "Romina Casaburi", phones: [], segment: "inattivi" },
  { name: "Salvatore Vecchio", phones: ["+393934113377"], segment: "inattivi" },
  { name: "Antonio Vellucci", phones: ["+393883775007"], segment: "inattivi" },
  { name: "Tiziano Gaudenzi", phones: ["+393403606465"], segment: "inattivi" },
  { name: "Paola Ruoppolo", phones: [], segment: "inattivi" },
  { name: "Michela D'aprano", phones: ["+393203553266"], segment: "inattivi" },
  { name: "Cristina Ruggiero", phones: ["+393478907408"], segment: "inattivi" },
  { name: "Domenico Pieruccini", phones: ["+393771114782"], segment: "inattivi" },
  { name: "Filippo Mazzucco", phones: ["+393498325866"], segment: "inattivi" },
  { name: "Nico Tumulo", phones: ["+393773972015"], segment: "inattivi" },
  { name: "Daniele Ieno", phones: ["+393495362665"], segment: "inattivi" },
  { name: "Antonio Anema e Core", phones: ["+393455814401"], segment: "abituali" },
  { name: "Edoardo D'aprano", phones: [], segment: "inattivi" },
  { name: "Pina D'aprano", phones: ["+393455671773"], segment: "inattivi" },
  { name: "Fabrizio Aniello", phones: ["+393791742004"], segment: "inattivi" },
  { name: "Lina Tirimb\u00f2", phones: [], segment: "inattivi" },
  { name: "Antonella Ianniello", phones: [], segment: "nuovi" },
  { name: "Maria assunta Falso", phones: ["+393388821913"], segment: "abituali" },
  { name: "Francesco Borrelli", phones: [], segment: "nuovi" },
  { name: "Diego Rubbeo", phones: ["+393313754712"], segment: "nuovi" },
  { name: "Ercole Sciorio", phones: [], segment: "abituali" },
  { name: "Fernando Vellucci", phones: ["+393483648503"], segment: "occasionali" },
  { name: "Erasmo Di Maio", phones: ["+393409086518"], segment: "occasionali" },
  { name: "Lillo Carbone", phones: ["+393388801081"], segment: "abituali" },
  { name: "Emiliano De paolis", phones: ["+393298340711"], segment: "occasionali" },
  { name: "Antonio Cassetta", phones: [], segment: "nuovi" },
  { name: "Amalia Ciorra", phones: ["+393473430113"], segment: "nuovi" },
  { name: "Alessandra Cardillo", phones: ["+393889988395"], segment: "abituali" },
  { name: "Claudio Bernardi", phones: ["+393383986490"], segment: "occasionali" },
  { name: "Antonella Riccitteli", phones: ["+393296241935"], segment: "abituali" },
  { name: "Attilio Vaduo", phones: [], segment: "nuovi" },
  { name: "Francesco Lombardi", phones: ["+393394795603"], segment: "abituali" },
  { name: "Emanuela Toma", phones: ["+393331436545"], segment: "nuovi" },
  { name: "Giuseppe Di Siena", phones: [], segment: "nuovi" },
  { name: "Gennaro Ianniello", phones: [], segment: "nuovi" },
  { name: "Gaia Tedesco", phones: [], segment: "nuovi" },
  { name: "Alessandro Ianniello", phones: [], segment: "nuovi" },
  { name: "Michelina Perrotta", phones: ["+393487073647"], segment: "abituali" },
  { name: "Anna", phones: [], segment: "abituali" },
  { name: "Vincenza Parente", phones: [], segment: "abituali" },
  { name: "Gennarino Mignano", phones: [], segment: "abituali" },
  { name: "Rossella Costanzo", phones: [], segment: "nuovi" },
  { name: "Elisabetta Testa", phones: [], segment: "nuovi" },
  { name: "Nietta Falso", phones: ["+393332684831"], segment: "abituali" },
  { name: "Patrizia Romano", phones: [], segment: "nuovi" },
  { name: "Giuseppe Ciorra", phones: ["+393476910497"], segment: "nuovi" },
  { name: "Cristian Lanterna", phones: [], segment: "nuovi" },
  { name: "Enrico Falso", phones: ["+393382035908"], segment: "nuovi" },
  { name: "Francesca Di nardo", phones: [], segment: "nuovi" },
  { name: "Carla Pimpinella", phones: ["+393495247536"], segment: "occasionali" },
  { name: "Marsilio Casale", phones: [], segment: "abituali" },
  { name: "Luciana Poccia", phones: [], segment: "occasionali" },
  { name: "Maria Rita Riccardi", phones: ["+393332737911"], segment: "nuovi" },
  { name: "Salvatore Manzo", phones: ["+393471919512"], segment: "abituali" },
  { name: "Lucia Ionta", phones: ["+393491767383"], segment: "occasionali" },
  { name: "Dario Iossa", phones: ["+393450160254"], segment: "nuovi" },
  { name: "Giovanni Testa", phones: ["+393204573076","+393474008109"], segment: "top" },
  { name: "Marzia Caddia", phones: ["+393280289382"], segment: "occasionali" },
  { name: "Vincenza Verrico", phones: ["+393277693260"], segment: "occasionali" },
  { name: "Adelina Improta", phones: ["+393892565729"], segment: "occasionali" },
  { name: "Francesco Vecchio", phones: ["+393470372645"], segment: "abituali" },
  { name: "Manuela Romanelli", phones: [], segment: "nuovi" },
  { name: "Gabriele Stabile", phones: [], segment: "nuovi" },
  { name: "Andrea Casale", phones: ["+393406696180"], segment: "occasionali" },
  { name: "Giulia Romanelli", phones: [], segment: "occasionali" },
  { name: "Maria Di Paola", phones: ["+393345969606"], segment: "nuovi" },
  { name: "Eufemia Domina", phones: ["+393403617853"], segment: "abituali" },
  { name: "Marianeve Marrese", phones: ["+393401717408"], segment: "nuovi" },
  { name: "Lidia Paraschiv", phones: ["+393791606006"], segment: "occasionali" },
  { name: "Angela Falso", phones: ["+393498374921"], segment: "occasionali" },
  { name: "Giuseppe Reccardo", phones: ["+393923243695"], segment: "abituali" },
  { name: "Angela Calegari", phones: [], segment: "nuovi" },
  { name: "Annamaria Toma", phones: ["+393358173735"], segment: "occasionali" },
  { name: "Federica Fantasia", phones: [], segment: "abituali" },
  { name: "Antonio Sciorio", phones: ["+393467106166"], segment: "abituali" },
  { name: "Elisa Ferro", phones: ["+393492312412"], segment: "abituali" },
  { name: "Monica Spinosi", phones: ["+393383322968"], segment: "abituali" },
  { name: "Gaetano Di Siena", phones: [], segment: "abituali" },
  { name: "Maria carmine Falso", phones: ["+393761550924"], segment: "abituali" },
  { name: "Luisa Perfetto", phones: ["+393483263394"], segment: "top" },
  { name: "Domenico Tibaldi", phones: ["+393351401352"], segment: "top" },
  { name: "Raffaele Ianniello", phones: ["+393357578704"], segment: "top" },
];

function norm(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, " ");
}

function uid(prefix: string): string {
  return prefix + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

/**
 * Applica la lista clienti sul vettore esistente:
 *  - se il cliente esiste (match per nome normalizzato): aggiorna segment (con segmentManual=true)
 *    e fonde i numeri di telefono (primario + phones[]) senza duplicati;
 *  - se non esiste: lo crea come Nuovo Cliente con segmento indicato e telefono se presente.
 */
export function applyClientImportV7(existing: Client[]): Client[] {
  const byName = new Map<string, Client>();
  for (const c of existing) byName.set(norm(c.name), c);

  const out: Client[] = [...existing];

  for (const item of CLIENT_IMPORT_V7) {
    const key = norm(item.name);
    const primary = item.phones[0] ?? "";
    const extras = item.phones.slice(1);
    const found = byName.get(key);

    if (found) {
      // Merge phones
      const all = new Set<string>();
      if (found.phone) all.add(found.phone);
      for (const p of (found.phones ?? [])) if (p) all.add(p);
      for (const p of item.phones) if (p) all.add(p);
      const phonesArr = Array.from(all);
      const newPrimary = found.phone || primary || phonesArr[0] || "";
      const newPhones = phonesArr.filter(p => p !== newPrimary);

      const idx = out.findIndex(c => c.id === found.id);
      out[idx] = {
        ...found,
        phone: newPrimary,
        phones: newPhones,
        segment: item.segment as Segment,
        segmentManual: true,
      };
      byName.set(key, out[idx]);
    } else {
      const created: Client = {
        id: uid("c_"),
        name: item.name,
        phone: primary,
        phones: extras,
        segment: item.segment as Segment,
        segmentManual: true,
        stamps: 0,
        firstOrder: new Date().toISOString().slice(0, 10),
        loyaltyHistory: [],
      };
      out.push(created);
      byName.set(key, created);
    }
  }

  return out;
}
