/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProdottiRouteImport } from './routes/prodotti'
import { Route as OrdiniRouteImport } from './routes/ordini'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as ConsegneRouteImport } from './routes/consegne'
import { Route as ClientiRouteImport } from './routes/clienti'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdottiRoute = ProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdiniRoute = OrdiniRouteImport.update({
  id: '/ordini',
  path: '/ordini',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsegneRoute = ConsegneRouteImport.update({
  id: '/consegne',
  path: '/consegne',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiRoute = ClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clienti': typeof ClientiRoute
  '/consegne': typeof ConsegneRoute
  '/offerte': typeof OfferteRoute
  '/ordini': typeof OrdiniRoute
  '/prodotti': typeof ProdottiRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clienti': typeof ClientiRoute
  '/consegne': typeof ConsegneRoute
  '/offerte': typeof OfferteRoute
  '/ordini': typeof OrdiniRoute
  '/prodotti': typeof ProdottiRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clienti': typeof ClientiRoute
  '/consegne': typeof ConsegneRoute
  '/offerte': typeof OfferteRoute
  '/ordini': typeof OrdiniRoute
  '/prodotti': typeof ProdottiRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clienti'
    | '/consegne'
    | '/offerte'
    | '/ordini'
    | '/prodotti'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clienti'
    | '/consegne'
    | '/offerte'
    | '/ordini'
    | '/prodotti'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clienti'
    | '/consegne'
    | '/offerte'
    | '/ordini'
    | '/prodotti'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientiRoute: typeof ClientiRoute
  ConsegneRoute: typeof ConsegneRoute
  OfferteRoute: typeof OfferteRoute
  OrdiniRoute: typeof OrdiniRoute
  ProdottiRoute: typeof ProdottiRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodotti': {
      id: '/prodotti'
      path: '/prodotti'
      fullPath: '/prodotti'
      preLoaderRoute: typeof ProdottiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordini': {
      id: '/ordini'
      path: '/ordini'
      fullPath: '/ordini'
      preLoaderRoute: typeof OrdiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consegne': {
      id: '/consegne'
      path: '/consegne'
      fullPath: '/consegne'
      preLoaderRoute: typeof ConsegneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti': {
      id: '/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof ClientiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientiRoute: ClientiRoute,
  ConsegneRoute: ConsegneRoute,
  OfferteRoute: OfferteRoute,
  OrdiniRoute: OrdiniRoute,
  ProdottiRoute: ProdottiRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
